name: Sync to Gitee

on:
  schedule:
    - cron: '0 0 * * * '
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate repo list
      id: repo
      uses: yi-Xu-0100/repo-list-generator@main
      
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/l1cardo
        dst: gitee/l1cardo
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: ${{ steps.repo.outputs.repoList }}
        clone_style: "ssh"
        force_update: true
        debug: true
